services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-container
        restart: always
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./mongo-tests-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
